### ISSUE TITLE
Query: What happens when the default logserver (gstatic/v2) goes down? Does the SDK have a "high availability" mechanism to fallback to a working logserver url? I am on version 1.1.1

### ISSUE THREAD

**Issue by gnair03** [appmattus/certificatetransparency#101]

**Comment by gnair03** [comment]
@mattmook Pls respond

**Comment by mattmook** [comment]
Hi @gnair03 in v1.x there is no fallback mechanism - if the service is down then as has been seen when Google removed the file the connection attempts then fail.

In v2, caching has been re-implemented and made a lot more robust. For example the library now embeds a hard coded log list so it always has a fallback. The implementation is closer to how Chrome works, if the library cannot update the log list for 70 days then the best it can do is disable the CT checks. The plan is for more regular updates of the library to keep the embedded log list in sync so as long as apps keep the library up to date that 70 days will keep on rolling - a disk cache being used also extends that 70 days too.
The new implementation additionally reduces the risk of replay attacks.
