### ISSUE TITLE
Deploy to maven?

### ISSUE THREAD

**Issue by pm-nchain** [appmattus/certificatetransparency#106]
- Version on maven: 2.5.19
- Version on GitHub release page: 2.5.30

**Comment by maxkohne** [comment]
@mattmook any updates here?

**Comment by stefanvinteler** [comment]
@mattmook any updates?
Version on maven: 2.5.19
Version on GitHub release page: 2.5.38

**Comment by andreiMaracineanu** [comment]
@mattmook any updates?
Version on maven: 2.5.19
Version on GitHub release page: 2.5.38
