### ISSUE TITLE
Provide support for using CT in China

### ISSUE THREAD

**Issue by mattmook** [appmattus/certificatetransparency#12]
www.gstatic.com is not accessible behind China's firewall, however www.gstatic.cn is available.

Determine what exception the library throws when connecting to gstatic.com and setup a retry based on that.

**Comment by mimi89999** [comment]
Why is it something that the lib should do?

**Comment by mattmook** [comment]
The current implementation means that if you use an app that has CT enabled in China then the connection will be disallowed as we cannot get a list of log servers.

The failure will not be obvious as to why it doesn't work or indeed how to fix it.

I'm personally of the viewpoint that I would like the library to work wherever you are in the world.

**Comment by mimi89999** [comment]
I think that the lib should not require to be able to connect to www.gstatic.com at all and instead embed the list.

**Comment by mattmook** [comment]
The list is constantly updated

**Comment by mimi89999** [comment]
> not updating it could mean your app trusts a log list server that was found to be be malicious.

That's why 2 signatures are required.

Android apps can also be updated very often, so I don't think that it would be a big issue. Logs for next year form current operators are already in the list, so only new operators would be an issue, but I don't think that they appear that often.

**Comment by mattmook** [comment]
You are putting an additional requirement on apps using the library that they have to be updated regularly. Not all apps are updated frequently.

Additionally the library isn't just Android this can be used in pure Java libraries and indeed is already being used outside of Android in a command line tool.

The library allows the user to implement their own log list DataSource, which can be a hard coded list if the user so wishes. It is left as an exercise for the user how they load and refresh this data.

**Comment by mattmook** [comment]
One thing I’m genuinely not sure about is how frequently you should update the list of log servers and their statuses. Chrome uses an embedded list, however, if I remember the code correctly, when the list is stale by a year it then no longer performs CT checks. Now typically major releases of Chrome are every 6 weeks with minor releases and security fixes every 2-3 weeks. So, I’m assuming Chrome updates its list every 2-3 weeks.

I had originally asked the question in the CT user group but didn’t get an answer at the time.

**Comment by shavinda-rabichandran-cko** [comment]
@mattmook Is there an easy way for a user to supply the `log_list.json` by hosting this file in their own domain.

Looking at the current implementation all the logic that parses the `log_list.json` is internal. 
A user wishing to host this and control the log_list.json within their own domain would essentially need to duplicate a number of classes that exist within the current library.

Do you feel there is a benefit to expanding the available options so;
   1. Default is loaded from www.gstatic.com as normal
   2. Alternate URL that hosts the same log_list.json can be provided (Rather than the www.gstatic.com URL) along with the publicKey used to verify the signature.
   3. Custom data source that loads the log_list.json from a file (utilising the parsing logic already existing within the library)

**Comment by mattmook** [comment]
@shavinda-rabichandran-cko yes I think there is some benefit to doing this, and would provide a solution for access from China nicely too.

**Comment by mattmook** [comment]
In the current implementation, URL can be overridden with the following:

```
certificateTransparencyInterceptor {
    logListService = LogListDataSourceFactory.createLogListService(
        baseUrl = "https://www.gstatic.com/ct/log_list/v3/"
    )
}
```

The next release will allow overriding the publicKey by setting a custom logListDataSource:

```
certificateTransparencyInterceptor {
    logListDataSource = LogListDataSourceFactory.createDataSource(
        publicKey = ByteArray(...),
        // if you are changing the base url you need to override logListService in the data source instead of directly in the main builder
        logListService = LogListDataSourceFactory.createLogListService(
            baseUrl = "https://www.gstatic.com/ct/log_list/v3/"
        )
    )
}
```

**Comment by mattmook** [comment]
As a follow-up, one scenario I was curious about is around the network failure use case. Once I've released the next version of the library it will contain an embedded version of the log-list so travelling to a country where you cannot update to the latest file won't cause any problems as there is always the embedded file as a backup.

**Comment by mattmook** [comment]
Given the above I'm happy there are enough workarounds in the library if someone wants to get CT checks working inside a country that cannot connect to gstatic.com.
