### ISSUE TITLE
Required method checkServerTrusted(X509Certificate[], String, String, String) missing error in Release Mode

### ISSUE THREAD

**Issue by UmerTaptap** [appmattus/certificatetransparency#123]
Application Class:

`
class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        installCertificateTransparencyProvider {
            // Setup a logger
            logger = BasicAndroidCTLogger(BuildConfig.DEBUG)

            // Setup disk cache
            diskCache = AndroidDiskCache(applicationContext)

//            +"abc.com"
            +"*.abc.com"
        }
    }
}

class CustomHurlStackCT : HurlStack() {
    override fun createConnection(url: URL): HttpURLConnection {
        val connection = super.createConnection(url)
        if (connection is HttpsURLConnection) {

            connection.hostnameVerifier = certificateTransparencyHostnameVerifier(connection.hostnameVerifier){
                println("Fail on error: ${this.failOnError}")
            }
        }
        return connection
    }
}

private fun makeNetworkRequest(url: String): CompletableFuture<Map<Boolean, String>> {
        val future = CompletableFuture<Map<Boolean, String>>()

        val requestQueue: RequestQueue = Volley.newRequestQueue(this, CustomHurlStack())

        val stringRequest = object : StringRequest(Method.GET, url,
            Response.Listener<String> { response ->
                // Log the response for debugging
                future.complete(mapOf(true to response))
            },
            Response.ErrorListener { error ->
                future.complete(mapOf(false to (error.message ?: "Unknown error")))
            }) {
            override fun getHeaders(): MutableMap<String, String> {
                val headers = mutableMapOf<String, String>()
                return headers
            }
        }

        requestQueue.add(stringRequest)
        return future
    }}
`

**Comment by dominikgold** [comment]
The consumer-proguard-rules are outdated as of right now. Add this to your own proguard rules for now and it'll work:
```
-keep class com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyTrustManagerBasic { *; }
-keep class com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyTrustManagerExtended { *; }
```

**Comment by UmerTaptap** [comment]
Thanks, its worked

**Comment by sudansh** [comment]
Still getting this error on "2.5.79" in webview.
I have explicitly added the [proguard rules](https://github.com/appmattus/certificatetransparency/issues/123#issuecomment-2262705049) even though they are now added in consumer proguard
