### ISSUE TITLE
Question for publish

### ISSUE THREAD

**Issue by charbgr** [appmattus/certificatetransparency#28]
When will you publish the new library with jdk15 to 19?

**Comment by mattmook** [comment]
hi @charbgr I'm hoping to create a build in the next week or so. Basically I want to add a fix for #17 first.

**Comment by mattmook** [comment]
Actually got most of the code in quite quickly today, there's some related tidy up to do in the sample app but that shouldn't take too long, so expect a new version a little sooner than I originally thought.
