### ISSUE TITLE
Crash with Android Gradle Plugin 7.1.0 on obfuscated release build (prior AGP versions are fine)

### ISSUE THREAD

**Issue by MatthewWhitmer** [appmattus/certificatetransparency#32]
There appears to be a crash associated with an obfuscated release build on the new AGP 7.1.0.  I can eliminate the crash by either reverting to AGP 7.0.4, setting minifyEnabled to false on the release configuration, or by removing this certificate transparency library. 

**Fatal Exception: java.lang.AbstractMethodError
abstract method "boolean android.support.v4.media.a.equals(java.lang.Object)"**

kotlin.jvm.internal.Intrinsics.areEqual (Intrinsics.java:8)
kotlinx.serialization.json.JsonImpl.validateConfiguration (JsonImpl.java:2)
kotlinx.serialization.json.JsonKt.Json (JsonKt.java:17)
com.appmattus.certificatetransparency.internal.loglist.parser.LogListJsonParserV2.<clinit> (LogListJsonParserV2.java:17)
com.appmattus.certificatetransparency.internal.loglist.parser.RawLogListToLogListResultTransformer.<init> (RawLogListToLogListResultTransformer.java:17)
com.appmattus.certificatetransparency.loglist.LogListDataSourceFactory.createDataSource (LogListDataSourceFactory.java:12)
com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyBase.<init> (CertificateTransparencyBase.java:12)
com.appmattus.certificatetransparency.internal.verifier.CertificateTransparencyInterceptor.<init> (CertificateTransparencyInterceptor.java:10)
com.appmattus.certificatetransparency.CTInterceptorBuilder.build (CTInterceptorBuilder.java:1)
com.appmattus.certificatetransparency.CTInterceptorBuilderExtKt.certificateTransparencyInterceptor (CTInterceptorBuilderExtKt.java:1)

**Comment by MatthewWhitmer** [comment]
I found a workaround.  You can add the following to 
**proguard-rules.pro**

-keep class kotlinx.serialization.** { *; }

(I realize the root cause is likely an AGP bug, but in the meantime maybe this workaround will help others affected)

**Comment by mattmook** [comment]
Thanks for the bug report.

It seems since last I updated Kotlinx Serialization have changed their recommended ProGuard rules.

I don't suppose you could try the following rules and see if that fixes the issue as I've been unable to replicate:

```
# Keep `Companion` object fields of serializable classes.
# This avoids serializer lookup through `getDeclaredClasses` as done for named companion objects.
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion Companion;
}

# Keep `serializer()` on companion objects (both default and named) of serializable classes.
-if @kotlinx.serialization.Serializable class ** {
    static **$* *;
}
-keepclassmembers class <1>$<3> {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep `INSTANCE.serializer()` of serializable objects.
-if @kotlinx.serialization.Serializable class ** {
    public static ** INSTANCE;
}
-keepclassmembers class <1> {
    public static <1> INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}

# @Serializable and @Polymorphic are used at runtime for polymorphic serialization.
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault
```

**Comment by MatthewWhitmer** [comment]
Those rules do not appear to help, it still crashes with the  java.lang.AbstractMethodError.   I bet it's some problem in the latest AGP, but still rather frustrating. 

Having the line below is the only thing that works for me (probably just a workaround for whatever the AGP bug is).  Not a huge deal to exclude most of an open source library from obfuscation. 

-keep class kotlinx.serialization.** { *; }

**Comment by MatthewWhitmer** [comment]
Just confirmed the issue still exists in the Android Gradle Plugin 7.1.1.  The workaround also continues to be effective.

**Comment by MatthewWhitmer** [comment]
I just re-tested with AGP 7.1.3 and it no longer appears to be an issue.
