### ISSUE TITLE
Migrate the CT log list dependency from v2 to v3

### ISSUE THREAD

**Issue by roger2hk** [appmattus/certificatetransparency#44]
Both the v1 and v2 CT log lists will be turned down on 17 October 2022.
https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/fX_AG-HUAQAJ

The latest CT log list URL is https://www.gstatic.com/ct/log_list/v3/log_list.json.

Here is the `log_list` code search result in this repo.
https://github.com/appmattus/certificatetransparency/search?p=1&q=log_list

**Comment by rbrauwers** [comment]
Anyone know what will happen after v1 and v2 CT log list shutdown?

The library will stop to work?

**Comment by rbrauwers** [comment]
I hope the maintainers of the library be 100% transparent about this critical issue.
If my understanding is correct, any client of this library will have his http requests refused after Oct 17, 2022, given that the v2 log list will be unaccessible.

More details on [this conversation](https://groups.google.com/g/certificate-transparency/c/otRk_9FZTEA).

cc: @mattmook

**Comment by alexandru-lachimov** [comment]
I emailed directly to chrome-certificate-transparency team and here is their reply.
<img width="1157" alt="Screen Shot 2022-09-21 at 08 52 24" src="https://user-images.githubusercontent.com/101573763/191424816-9bbe1b30-b5fc-45f3-b455-cff4db0afebd.png">
<img width="1153" alt="Screen Shot 2022-09-21 at 08 52 32" src="https://user-images.githubusercontent.com/101573763/191424837-85f49660-0370-4fa6-a4cd-69d952b5d386.png">

**Comment by roger2hk** [comment]
Joe is right. The painess upgrade is to update the following endpoint from v2 to v3 and the code comments.

https://github.com/appmattus/certificatetransparency/blob/80e835fe1d67d848215a614646ca20e9c3f07026/certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/loglist/LogListDataSourceFactory.kt#L49

**Comment by alexandru-lachimov** [comment]
PR is opened -> https://github.com/appmattus/certificatetransparency/pull/47
FYI @mattmook

**Comment by rbrauwers** [comment]
Thanks for you support.

Just to be clear, even with a quick release of a version using v3 list log, certificate transparency clients will have a short window to update their apps (˜25 days).

Any help to kindly ask Google to postpone the v2 turndown on 17 October 2022 is appreciated.

**Comment by alexandru-lachimov** [comment]
Clients had more than one moth to migrate to V3, I have some doubts that guys Google will change their mind and postpone V1 and V2 endpoints shout-down.

**Comment by rbrauwers** [comment]
My hope is low too. But i think it's worth a try.

Clients has LESS than one month to migrate to V3.
This is not much time, specially to libraries that uses certificate transparency, needing to propagate the update to their clients.

**Comment by alexandru-lachimov** [comment]
Looks like **CTTrustManagerBuilder**, **CTInterceptorBuilder**  and **CTHostnameVerifierBuilder** builders have an option to provide custom **LogListService** using Factory **LogListDataSourceFactory.createLogListService("urlToOverride", " okHttpClientToOverride", "timeOutToOverride")**

**Comment by roger2hk** [comment]
> Looks like **CTTrustManagerBuilder**, **CTInterceptorBuilder** and **CTHostnameVerifierBuilder** builders have an option to provide custom **LogListService** using Factory **LogListDataSourceFactory.createLogListService("urlToOverride", " okHttpClientToOverride", "timeOutToOverride")**

Thanks for looking into that. The log list v3 should be backward compatible with v2, so overriding the `baseUrl` is the workaround when the fix is not yet released.

**Comment by alexandru-lachimov** [comment]
Yeap, that looks like to be an option to solve the problem without a relese.

**Comment by perwyl** [comment]
> Looks like **CTTrustManagerBuilder**, **CTInterceptorBuilder** and **CTHostnameVerifierBuilder** builders have an option to provide custom **LogListService** using Factory **LogListDataSourceFactory.createLogListService("urlToOverride", " okHttpClientToOverride", "timeOutToOverride")**

Hi @alexandru-lachimov is this sufficient for the workaround? I tested fine but unable to print out the base url to check if it's using v3. 

```
   private fun customCTInterceptorBuilder(): CTInterceptorBuilder {
        val logListV3 = LogListDataSourceFactory.createLogListService(
            baseUrl = CT_LOG_BASE_URL_V3 //"https://www.gstatic.com/ct/log_list/v3/"
        )

        val failureLogger = object : CTLogger {
            override fun log(host: String, result: VerificationResult) {
                Log.d(CT_TAG, "$host -> $result")
                if (result is VerificationResult.Failure) {
                    Tracer.error(CT_TAG, "$host -> $result")
                }
            }
        }

        return CTInterceptorBuilder()
            .setLogListService(logListV3)
            .setLogger(failureLogger)
            .includeHost(XXX")
    }
```

**Comment by alexandru-lachimov** [comment]
Hi @perwyl. Yes, it should be fine. You can clone the project and check LogListService usages and its implementation. 
Hope @mattmook  will be back soon to approve and merge this PR. Good news from @roger2hk that turndown V1 and V2 endpoints was delayed.

**Comment by kamilargent** [comment]
@mattmook could u please merge this PR and release a new version? The endpoints will be shut down next month and we would like to migrate our apps without any workarounds.

**Comment by kvetis** [comment]
Hi, posting minimal code to fix the interceptor (works for us):

```
certificateTransparencyInterceptor {
        setLogListService(LogListDataSourceFactory.createLogListService("https://www.gstatic.com/ct/log_list/v3/"))
}
```

**Comment by kamilargent** [comment]
> Hi, posting minimal code to fix the interceptor (works for us):
> 
> ```
> certificateTransparencyInterceptor {
>         setLogListService(LogListDataSourceFactory.createLogListService("https://www.gstatic.com/ct/log_list/v3/"))
> }
> ```

I can confirm that it's working - we ended up doing the exact thing a couple of weeks back. I am just worried that not everyone will come across this thread when integrating the library for the 1st time :(

**Comment by EvgeniyMish** [comment]
> ```kotlin
> https://www.gstatic.com/ct/log_list/v3/
> ```

How can you test this code ?

**Comment by roger2hk** [comment]
Here is the update on v2 log list and CT on Android.
https://groups.google.com/g/certificate-transparency/c/38Lr9K46cCA
