### ISSUE TITLE
Incorrect invoke call for the isSameTrustConfigurationMethod

### ISSUE THREAD

**Issue by dustinsummers** [appmattus/certificatetransparency#46]
Hey, just opened a quick PR to fix the invoke of the isSameTrustConfigurationMethod call.  We weren't passing in the `delegate` trust manager with the reflected method call, so I'm not sure that would have actually worked without it?  

https://github.com/appmattus/certificatetransparency/pull/45

**Comment by mattmook** [comment]
Yes that was a silly mistake on my part. Thanks for the PR to fix
