### ISSUE TITLE
Google Play Blocker: Unsafe SSL TrustManager Defined

### ISSUE THREAD

**Issue by EvgeniyMish** [appmattus/certificatetransparency#50]
Running a security scan on an .apk that uses certificate-transparency lib outputs the following problem:
Google Play **blocker**:
**Regardless** of whether the affected classes are actually used at runtime or not, Google Play is **blocking** any App that defines such an insecure `X509TrustManager`, as detailed on [Google's support page](https://support.google.com/faqs/answer/6346016):
 > "Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager."
 
 The root cause is in the BouncyCastle bcprov lib, which is a dependency of certificate-transparency. The class with insecure TrustManager is : https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/est/jcajce/JcaJceUtils.java
 
 The questions are: 
 1. There are lot of applications using certificate-transparency in the GooglePlay Store now. Did you ever faced such issue/request for information/blocked application ?
 2. Is there a possibility that certificate-transparency library won't import that class from BouncyCastle ? 
 Thanks.

**Comment by mattmook** [comment]
Annoyingly bcprov is a transitive dependency of most of bouncycastle... over next few days I'm going to see what I can do to remove BC as a dependency of the project - I've been wanting to get rid of it for some time now just never had the right motivation.

**Comment by mattmook** [comment]
Have now merged in a PR which removes BC - a little bit more work than I expected/hoped for but all unit tests are passing successfully now
