### ISSUE TITLE
v2 log list issue and behaviours on older app version

### ISSUE THREAD

**Issue by mpatafio** [appmattus/certificatetransparency#54]
Hi guys, 

I'm using `com.appmattus.certificatetransparency:certificatetransparency-android:0.2.0` in my Android app. I just noticed this from the Google Play Developer Console

![image](https://user-images.githubusercontent.com/6072188/211496888-847f25da-44a8-43c4-953a-9469638255bb.png)

The message is clear and an update for my app is needed. 

I've just one doubt about older versions of the app that implement the above library version: do all the network calls fail starting from the 15th of February 2023? Or just the CT check during SSL handshake won't work gracefully?

Thank you in advance.

**Comment by HappyDr0id** [comment]
@mpatafio Indeed all network calls for older versions that still use v2 will stop working starting this date. So you have around a month to do your best to migrate all your users, I've been through this on my side too 😕
If you didn't see this ticket yet, it contains all the context: https://github.com/appmattus/certificatetransparency/issues/44

**Comment by mpatafio** [comment]
Thank you @HappyDr0id. 

One question for the future: how can I get notified in case of further log list endpoint turndown? How often they will be discontinued?

**Comment by jdeblasio** [comment]
@mpatafio Chrome CT person here.

We try to avoid updating the schema / URL for the list whenever possible, and changes are announced ahead of time on the ct-policy@chromium mailing list, viewable at https://groups.google.com/a/chromium.org/g/ct-policy .

Note that this log list is designed to be used by certificate authorities and related parties who need to ensure that their certificates are trusted in Chrome. If apps or libraries build CT enforcement into their own apps using this list, they do so at their own risk -- we can't make any guarantees about the stability of the list, and in general we can't change our timelines to accommodate non-Chrome use-cases.

**Comment by jdeblasio** [comment]
@daniel-tailored speaking only for myself (not for Chrome or Google):

Most of the risk here comes from apps relying on libraries that aren't maintained. It might be reasonable for an app or library to bootstrap their CT enforcement using the Chrome list, but the CT ecosystem is always evolving, so to do so safely, the app/library developer is taking an ongoing obligation to keep up with changes to the ecosystem to keep things up to date. 

This is similar to the other risks developers face when using third-party libraries. Unmaintained libraries might, for instance, have unpatched security vulnerabilities. App developers take on the cumulative risk of all of their dependencies.

Unfortunately, I'm not aware of an actively-maintained CT library for Android at this time. This functionality also isn't provided by Google Play Services or other Google-supported libraries.

As a result, I suspect developers have two options:
 * Not use CT, nor pinning. Rely on the standard protections provided by TLS. You can further mitigate these risks by using things technologies like CAA to reduce the set of sources for unauthorized certificates.
 * Use certificate pinning anyway, but mitigate the pinning risks by providing multiple backup pins and re-evaluating your pinning configuration regularly.
 * Use CT, but ensure your dependencies maintain compatibility. In this case, that might mean monitoring the mailing list mentioned above carefully for any changes that might impact your app, and testing or modifying your configuration as needed.

I know that none of those are super satisfying answers.

**Comment by mattmook** [comment]
A new version will be released shortly that will address the URL change and also provide a more robust caching mechanism.

Of particular note there are now some different VerificationResults to take note of that can help from a monitoring point of view.

- *VerificationResult.Success.StaleNetwork* - This indicates that the timestamp of the log-list.json file from the network is out of date. There are two cases here:
  - either there is already cached data that is newer than the server is presenting; possible replay attack
  - or there is no cached data and we are returning the server data as presented; possible network issues
- *VerificationResult.DisableChecks* - This indicates we are unable to load new data from the server and the data we do have is greater than 70 days old so (like Chrome) we are failing soft and disabling CT checks.
