### ISSUE TITLE
CTPolicy failing with 2.x

### ISSUE THREAD

**Issue by denzilferreira** [appmattus/certificatetransparency#81]
In development, we are upgrading the library to 2.1.1 (we also tried 2.0.0 and 2.1.0). We are seeing this error on the log, unable to connect to a valid URL:

```bash
URL Failure: Too few distinct operators, required 3, found 2 in [7s3QZNXbGs7FXLedtM0TojKHRny87N7DUUhZRnEftZs=:Valid SCT, c9meiRtMlnigIH1HneayxhzQUV5xGSqMa4AQesF3crU=:Valid SCT, SLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHM=:Valid SCT]
```

If I'm understanding this correctly, we have 3 valid SCT, but found says it's only 2? Do you know if this is a bug?

**Comment by denzilferreira** [comment]
@mattmook let me know if you need more info to debug this. Thanks!

**Comment by denzilferreira** [comment]
For context, v1.1.1 for the same URL reports all OK:
<img width="2038" alt="image" src="https://user-images.githubusercontent.com/8342829/229818696-3190ac72-9e8e-4778-80af-80a51c3003f0.png">

**Comment by mattmook** [comment]
hmm, that doesn't read right, let me take a look and see what I can see

**Comment by denzilferreira** [comment]
Thanks!
