### ISSUE TITLE
App size increased by 2.2 MB

### ISSUE THREAD

**Issue by gnair03** [appmattus/certificatetransparency#92]
On using this SDK, my app-size has increased by 2.2MB. What could be the cause of this increase? Are there any ways to reduce app size increase due to this lib?

**Comment by gnair03** [comment]
@mattmook 
Pls let me know

**Comment by mattmook** [comment]
The jar for the CT library comes in at ~500k and the latest version of the library pulls in the following dependencies:

- com.squareup.okhttp3:okhttp
- org.jetbrains.kotlin:kotlin-stdlib-jdk8
- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm
- org.jetbrains.kotlinx:kotlinx-serialization-json-jvm

My only suggestion size wise is to ensure you use R8 on your project as I'm unlikely to be able to reduce the dependencies currently used.
