### ISSUE TITLE
Missing classes detected while running R8 with AGP > 8

### ISSUE THREAD

**Issue by EvgeniyMish** [appmattus/certificatetransparency#96]
Trying to compile the project getting the following error:
```
Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /.../.../build/outputs/mapping/.../missing_rules.txt.
Missing class java.lang.invoke.StringConcatFactory (referenced from: void CertificateTransparencyLogger.log(java.lang.String, com.appmattus.certificatetransparency.VerificationResult) and 12 other contexts)
```

**Comment by mattmook** [comment]
Related to https://github.com/Kotlin/kotlinx.serialization/issues/2145? Looks like I should be able to tweak the compiler options with the following when building the library to prevent this:

```
freeCompilerArgs = listOf("-Xstring-concat=inline")
```

**Comment by mattmook** [comment]
I think part of the reason why I hadn't seen this before is the apps I'm using the library in personally are built with Java 11. I assume yours is built with Java 8 currently?
