### ISSUE TITLE
DataSource reuseInflight job gets stuck in a cancelled state

### ISSUE THREAD

**Issue by sudojhill** [appmattus/certificatetransparency#97]
Maybe I am not fully understanding the code in `DataSource . reuseInflight ` but if `job` gets cancelled before the line with `launch` gets called, then `job` is stuck in a cancelled state and subsequent calls to `get()` immediately fail. My app seemed to be getting into this situation and couldn't recover.

For reference:
```
override suspend fun get(): Value? {
    return coroutineScope {
        job ?: async { this@DataSource.get() }.apply {
            job = this

            launch {
                this@apply.join()
                job = null
            }
        }
    }.await()
}
```

Adding `job?.invokeOnCompletion { job = null }` seems to fix the issue I was experiencing:
 ```
override suspend fun get(): Value? {
    return coroutineScope {
        job ?: async { this@DataSource.get() }.apply {
            job = this
            job?.invokeOnCompletion { job = null }

            launch {
                this@apply.join()
                job = null
            }
        }
    }.await()
}
```

**Comment by mattmook** [comment]
Yes, this looks like a sensible solution and probably should have always been written like this! I've created a unit test that shows this solution works (and breaks on the original code)
